---
# This Playbook would deploy elasticsearch/logstash/filebeat

- hosts: all
  roles:
  - role: common
  tags:
    - install_all
    - install

- hosts: elasticsearch_servers
  sudo: true
  roles:
  - role: elasticsearch
  tags:
    - install_elasticsearch

- hosts: logstash_servers
  sudo: true
  roles:
  - role: logstash
  tags:
    - install_logstash
- hosts: beats_servers
  sudo: true
  roles:
  - role: beats
  tags:
    - install_filebeat

#- hosts: elasticsearch_servers
#  tasks:
#  - include: roles/logstash/tasks/shards.yml