---
# This Playbook would deploy elasticsearch/logstash/filebeat

- hosts: all
  roles:
  - role: common

- hosts: elasticsearch_servers
  sudo: true
  roles:
  - role: elasticsearch

- hosts: logstash_servers
  sudo: true
  roles:
  - role: logstash

- hosts: beats_servers
  sudo: true
  roles:
  - role: beats

#- hosts: elasticsearch_servers
#  tasks:
#  - include: roles/logstash/tasks/shards.yml