---
# This Playbook would deploy elasticsearch/logstash/filebeat

- hosts: all
  roles:
  - role: common
  tags:
    - install_all
    - install
    - install_elasticsearch
    - install_logstash
    - install_filebeat

- hosts: elasticsearch_servers
  become: true
  roles:
  - role: elasticsearch
  tags:
    - install_elasticsearch

- hosts: logstash_servers
  become: true
  roles:
  - role: logstash
  tags:
    - install_logstash
- hosts: filebeat_servers
  become: true
  roles:
  - role: filebeat
  tags:
    - install_filebeat

#- hosts: elasticsearch_servers
#  tasks:
#  - include: roles/logstash/tasks/shards.yml