---
- hosts: all
  gather_facts: False
  tasks:
  - name: 1. MAKE DIR
    file:
      path: /home/admin/publish/{{project}}/{{module}}/{{ item.sub_dir }}
      group: admin
      owner: admin
      state: directory
    with_items:
      - {sub_dir: "lastest"}
      - {sub_dir: "script"}

  - name: 2. STOP SERVICE
    shell: chdir=/opt/tomcat/{{module}}/ ./stop.sh

  - name: 3 COPY UPDATE.SH TO HOSTS
    copy:
      src="{{ local_scripts_dir }}/scripts/{{project}}/{{module}}/update.sh"
      dest="{{ remote_scripts_dir }}/scripts/{{project}}/{{module}}/update.sh"
      owner=admin
      group=admin
      mode=0755

  - name: 4. RUN UPDATE SCRIPT
    script: '{{ remote_scripts_dir }}/scripts/{{project}}/{{module}}/update.sh {{env}} {{project}} {{module}} {{version}} {{build}}'

  - name: 5. START SERVICE
    shell: chdir=/opt/tomcat/{{module}}/ ./start.sh

