---
## This role deploys the mongod processes and sets up the replication set.
#
#- name: create data directory for mongodb
#  file: path={{ mongodb_datadir_prefix }}/mongo-{{ inventory_hostname }} state=directory owner=mongod group=mongod
#  delegate_to: '{{ item }}'
#  with_items: "{{ groups.replication_servers }}"
#
#- name: create log directory for mongodb
#  file: path=/var/log/mongo state=directory owner=mongod group=mongod
#
#- name: create run directory for mongodb
#  file: path=/var/run/mongo state=directory owner=mongod group=mongod
#
#- name: Create the mongodb startup file
#  template: src=mongod.j2 dest=/etc/init.d/mongod-{{ inventory_hostname }} mode=0655
#  delegate_to: '{{ item }}'
#  with_items: "{{ groups.replication_servers }}"
#
#
#- name: Create the mongodb configuration file
#  template: src=mongod.conf.j2 dest=/etc/mongod-{{ inventory_hostname }}.conf
#  delegate_to: '{{ item }}'
#  with_items: "{{ groups.replication_servers }}"
#
#- name: Create the mongodb service file
#  template: src=mongod.service.j2 dest=/run/systemd/generator.late/mongod-{{ inventory_hostname }}.service
#  delegate_to: '{{ item }}'
#  with_items: "{{ groups.replication_servers }}"
#
#- name: Create soft link to mongodb service file
#  file: src=/run/systemd/generator.late/mongod-{{ inventory_hostname }}.service
#        dest=/run/systemd/generator.late/runlevel3.target.wants/mongod-{{ inventory_hostname }}.service state=link
#  delegate_to: '{{ item }}'
#  with_items: "{{ groups.replication_servers }}"
#
#- name: Create soft link to mongodb service file
#  file: src=/run/systemd/generator.late/mongod-{{ inventory_hostname }}.service
#        dest=/run/systemd/generator.late/runlevel5.target.wants/mongod-{{ inventory_hostname }}.service state=link
#  delegate_to: '{{ item }}'
#  with_items: "{{ groups.replication_servers }}"
#
##- name: Copy the keyfile for authentication
##  copy: src=secret dest={{ mongodb_datadir_prefix }}/secret owner=mongod group=mongod mode=0400
#
#
#- name: Start the mongodb service
#  command: creates=/var/lock/subsys/mongod-{{ inventory_hostname }} /etc/init.d/mongod-{{ inventory_hostname }} start
#  delegate_to: '{{ item }}'
#  with_items: "{{ groups.replication_servers }}"
#
#- name: Create the file to initialize the mongod replica set
#  template: src=repset_init.j2 dest=/tmp/repset_init.js
#
#- name: Pause for a while
#  pause: seconds=20
#
#- name: Initialize the replication set
#  shell: /usr/bin/mongo --port "{{ mongod_port }}" /tmp/repset_init.js

- name: check logstash servers date
  command: date

- name: prepare for install, mkdir "{{ logstash_get_path }}"
  file: dest="{{ logstash_get_path }}" state=directory

- name: download logstash compression package "{{ logstash_get_url }}", to "{{ logstash_get_path }}"/"{{ logstash_get_name }}"
  get_url: url="{{ logstash_get_url }}" dest="{{ logstash_get_path }}"/"{{ logstash_get_name }}"

- name: uncompress package "{{ logstash_get_path }}"/"{{ logstash_get_name }}" to "{{ logstash_get_path }}"
  shell: cd "{{ logstash_get_path }}" && tar xzf "{{ logstash_get_name }}"

- name: mkdir for pattern files, mkdir "{{ logstash_get_path }}"/patterns
  file: dest="{{ logstash_get_path }}" state=directory

- name: copy pattern files to "{{ logstash_get_path }}"/patterns
  template: src=nginx.j2 dest="{{ logstash_get_path }}"/patterns/nginx.conf

- name: copy nginx config file to "{{ logstash_get_path }}"/logstash-5.3.0/bin
  template: src=logstash-nginx.conf.j2 dest="{{ logstash_get_path }}"/logstash-5.3.0/bin/logstash-nginx.conf