---
- hosts: "{{host}}"
  gather_facts: False
  tasks:
  - name: 1. MAKE DIR
    become: yes
    file:
      path: /home/admin/release/tmp/{{version}}
      group: admin
      owner: admin
      state: directory
    with_items:
      - {sub_dir: "lastest"}
  - name: 2. DOWNLOAD VERSION
    become: yes
    get_url:
      url: "{{item.file_url}}"
      dest: "/home/admin/release/tmp/{{version}}/{{item.file_name}}"
      checksum: "md5:{{item.md5}}"
      owner: admin
      group: admin
    with_items: "{{ file_list }}"