---

- hosts: all
  gather_facts: false

  tasks:
  - name: check date on the server.
    command: date

  - name: check if /opt/app directory exists.
    command: cd /opt/app

  - name: check if /opt/app/install dircetory exists.
    command: cd /opt/app/install 
  
  - name: get /opt/app/install directories 
    shell: ls -l /opt/app/install | grep '^d' | awk '{print $9" -> "$10}'
    register: result2

  - name: print result2 
    debug: msg={{ result2.stdout }}
    when: result2.stdout is defined
