---

- hosts: all
  gather_facts: no

  tasks:
  - name: Check the date on the host.
    command: date

  - name: install many software
    yum: name={{ item }} state=present
    with_items: "{{ apps_list }}"

#  - name: get apps.
#    delegate_to: localhost
#    shell: echo {{ apps_name_version }} | awk -F, '{print $1"\n"$2}'
#    register: apps_list
#    ignore_errors: True

  - name: check apps installed
    shell: yum info {{ item }} | grep Installed
    with_items: "{{ apps_list }}"
