---

- hosts: all
  gather_facts: no

  tasks:
  - name: Check the date on the host.
    command: date

  - name: install software {{ app_name }} of the latest version
    yum: name={{ app_name }} state=present
    when: app_version is undefined or app_version == ""

  - name: install software {{ app_name }} of version {{ app_version }}
    yum: name={{ app_name }}-{{ app_version }} state=present
    when: app_version is defined and app_version != ""

  - name: check {{ app_name }} has been installed in installed list
    shell: yum list installed | grep ^{{ app_name }}
    register: result1
    ignore_errors: True

  - name: check {{ app_name }} has been installed using yum list.
    shell: yum list {{ app_name }} | grep Installed
    register: result2
    ignore_errors: True

  - name: check {{ app_name }} has been installed using yum info.
    shell: yum info {{ app_name }} | grep Installed
    register: result3
    ignore_errors: True

  - name: if not find {{ app_name }} fail this task.
    fail: msg="can not find {{ app_name }}, please check!!!"
    when: result1.rc != 0 and result2.rc != 0 and result3.rc != 0
