---

- hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: 0. Check the date on the host.
    command: date

  - name: 1. make yum.repos.backup.d backup dir
    file:
      path: /etc/yum.repos.backup.d
      group: root
      owner: root
      state: directory

  - name: 2. download internal yum repo file
    get_url:
      url: http://10.106.71.5/centos/CentOS-EJU.repo
      dest: /etc/yum.repos.d/CentOS-EJU.repo
      checksum: "md5:6b61f40741ab8f4f28f95a5535b9901e"
      owner: root
      group: root
      force: no

  - name: 3. move repo files to backup dir
    shell: mv /etc/yum.repos.d/* /etc/yum.repos.backup.d/


  - name: 4. stat internal repo file
    stat:
      path: /etc/yum.repos.backup.d/CentOS-EJU.repo
    register: repo_stat

  - name: 5. Move internal repo file to yum.repo.d
    command: mv /etc/yum.repos.backup.d/CentOS-EJU.repo /etc/yum.repos.d/CentOS-EJU.repo
    when: repo_stat.stat.exists

#  - name: 5. Move internal repo file to yum.repo.d
#    copy:
#      remote_src: True
#      src: /etc/yum.repos.backup.d/CentOS-EJU.repo
#      dest: /etc/yum.repos.d/CentOS-EJU.repo
#    when: repo_stat.stat.exists
