---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: add repo file
    yum_repository:
      name: CentOS-EJU
      description: add internal yum CentOS-EJU.repo
      baseurl:  http://10.106.71.5/centos/CentOS-EJU.repo

