---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: 1. download internal yum repo file
    get_url:
      url: http://10.106.71.5/centos/CentOS-EJU.repo
      dest: /etc/yum.repos.d/CentOS-EJU.repo
      checksum: "md5:6b61f40741ab8f4f28f95a5535b9901e"
      owner: root
      group: root
      force: no

