---
#
# Install/run elasticsearch
#

- name: Copy elasticsearch yum repo file
  copy:
    src=elasticsearch.repo
    dest=/etc/yum.repos.d/elasticsearch.repo
    mode=0644

- name: Install elasticsearch and openjdk
  yum: name={{ item }} state=present
  become: true
  with_items:
    - elasticsearch
    - java-openjdk-headless

- name: Start elasticsearch service
  command: systemctl start elasticsearch.service
  ignore_errors: true

- name: Setup elasticsearch service
  service: name=elasticsearch state=started enabled=true
  become: true