---
#
# Install/run elasticsearch
#

- name: Copy elasticsearch yum repo file
  copy:
    src=elasticsearch.repo
    dest=/etc/yum.repos.d/elasticsearch.repo
    owner=root
    group=root
    mode=0644

- name: Install elasticsearch and openjdk
  yum: name={{ item }} state=present
  with_items:
    - elasticsearch-{{ version }}
    - java-openjdk-headless

- name: Generate elasticsearch configuration template
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=root
    mode=0644
  register: elasticsearch_needs_restart

# just start now, not really restart
- name: Start elasticsearch service
  command: systemctl start elasticsearch.service
  ignore_errors: true
  when: elasticsearch_needs_restart != 0

- name: Setup elasticsearch service
  service: name=elasticsearch state=started enabled=true

- name: create cron job to clean es indices...
  cron:
    name="clean es indices.."
    job="/usr/bin/curl -u {{ es_user }}:{{ es_password }}  -H'Content-Type:application/json' -d'{"query":{"range":{"@timestamp":{"lt":"now-{{ es_reserve_indeices }}","format":"epoch_millis"}}}}' -XPOST "http://127.0.0.1:{{ es_http_port }}/*-*/_delete_by_query?pretty" > /tmp/elk_clean.txt"
    user=root
    day="{{ es_clean_interval_of_day }}"
  when: es_need_clean_indices
