logstash:
  get:
    path: /opt/logstash
    url: https://artifacts.elastic.co/downloads/logstash/logstash-5.3.0.tar.gz
    name: logstash-install-5.3.0.tar.gz

  filter:
    type:
      nginx:
        access:
          value: nginx_access
          patterns_dir: /opt/logstash/patterns
          message: %{NGINXACCESSONE}
        error:
          value: nginx_error
          patterns_dir: /opt/logstash/patterns
          message: %{NGINXERRORONE}
  output:
    type:
      access:
        value: nginx_access
        es:
          hosts:
            - "localhost:9200"
          user: elastic
          pass: changeme
          index: logstash-%{[@metadata][beat]}-access-%{+YYYY.MM.dd}
          doc_type: %{[@metadata][type]}
      error:
        value: nginx_error
        es:
          hosts:
            - "localhost:9200"
          user: elastic
          pass: changeme
          index: logstash-%{[@metadata][beat]}-error-%{+YYYY.MM.dd}
          doc_type: "%{[@metadata][type]}"

