logstash_get_path: /opt/logstash
logstash_get_url: https://artifacts.elastic.co/downloads/logstash/logstash-5.3.0.tar.gz
logstash_get_name: logstash-install-5.3.0.tar.gz

logstash_filter_access_value: nginx_access
logstash_filter_access_patternsdir: /opt/logstash/patterns
logstash_filter_access_message: {NGINXACCESSONE}
logstash_filter_error_value: nginx_error
logstash_filter_error_patternsdir: /opt/logstash/patterns
logstash_filter_error_message: {NGINXERRORONE}

logstash_output_access_value: nginx_access
logstash_output_access_es_hosts: ["localhost:9200"]
logstash_output_access_es_user: elastic
logstash_output_access_es_pass: changeme
logstash_output_access_es_index: logstash-%{[@metadata][beat]}-access-%{+YYYY.MM.dd}
logstash_output_access_es_doctype: {[@metadata][type]}
logstash_output_error_value: nginx_error
logstash_output_error_es_hosts: ["localhost:9200"]
logstash_output_error_es_user: elastic
logstash_output_error_es_pass: changeme
logstash_output_error_es_index: logstash-%{[@metadata][beat]}-error-%{+YYYY.MM.dd}
logstash_output_error_es_doctype: {[@metadata][type]}


