---
#This Playbook configures the mongos service of mongodb

- name: Create the mongos startup file
  template: src=mongos.j2 dest=/etc/init.d/mongos mode=0655


- name: Create the mongos configuration file
  template: src=mongos.conf.j2 dest=/etc/mongos.conf

- name: Create the mongos service file
  template: src=mongos.service.j2 dest=/run/systemd/generator.late/mongos.service

- name: Create soft link to mongos service file
  file: src=/run/systemd/generator.late/mongos.service
        dest=/run/systemd/generator.late/runlevel3.target.wants/mongos.service state=link

- name: Create soft link to mongos service file
  file: src=/run/systemd/generator.late/mongos.service
        dest=/run/systemd/generator.late/runlevel5.target.wants/mongos.service state=link

#- name: Copy the keyfile for authentication
#  copy: src=roles/mongod/files/secret dest={{ mongodb_datadir_prefix }}/secret owner=mongod group=mongod mode=0400

- name: Start the mongos service
  command: creates=/var/lock/subsys/mongos /etc/init.d/mongos start
- name: pause
  pause: seconds=20

- name: copy the file for shard test
  template: src=testsharding.j2 dest=/tmp/testsharding.js

- name: copy the file enable  sharding
  template: src=enablesharding.j2 dest=/tmp/enablesharding.js
