---

- name: check logstash servers date
  command: date

- name: check if logstash has been started.
  shell: ps -ef | grep /logstash/.*{{ logstash_config }} | grep -v grep
  register: result
  ignore_errors: True

- name: stop logstash service
  shell: kill {{ logstash_stop_kill_args }} `ps -ef | grep /logstash/.*{{ logstash_config }} | grep -v grep | awk '{print $2}'`
  when: result.rc == 0

- name: logstash service has been stopped or not started yet....
  debug: msg="logstash service has been stopped or not started yet....do nothing"
  when: result.rc == 1